@startuml
'skinparam packageStyle rectangle
title How user interacts with application

left to right direction

actor Guest
usecase "Registration" as Reg
Guest --> Reg


actor User
usecase "Login" as Log
usecase "Create document" as CreateDoc
usecase "Select document`s template" as SelectTemplate
usecase "Read document" as ReadDoc
usecase "Edit document" as EditDoc
usecase "Save document" as SaveDoc
usecase "Send document to signature" as SendDocToSign
usecase "Sign document" as SignDoc

User --> Log
User --> CreateDoc
CreateDoc ..> SelectTemplate : include
User --> ReadDoc
User --> EditDoc
User --> SaveDoc
User --> SendDocToSign
User --> SignDoc


actor Admin
Admin -left->> User
usecase "Create DocDraft" as CreateDocDraft
Admin -> CreateDocDraft

database "Document storage" as Db
SelectTemplate -> Db
Db -up-> ReadDoc

@enduml
